# Generated by Django 3.0.8 on 2020-07-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
