# Generated by Django 3.0.8 on 2020-07-23 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0003_auto_20200720_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio_total',
        ),
    ]
