# Generated by Django 3.0.8 on 2020-07-24 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0004_remove_pedido_precio_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza_ing',
            name='fk_ingrediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Ingrediente'),
        ),
    ]
