# Generated by Django 3.0.8 on 2020-07-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0005_auto_20200724_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_ing',
            name='num_pizza',
            field=models.IntegerField(default=1),
        ),
    ]
