# Generated by Django 3.0.8 on 2020-08-01 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0006_pizza_ing_num_pizza'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pizza_ing',
            options={'verbose_name_plural': 'Ventas'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='precio_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=20, verbose_name='Apellido Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='Nombre Cliente'),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='nombre',
            field=models.CharField(max_length=12, verbose_name='Ingrediente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fk_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(max_length=9, verbose_name='Tamaño Pizza'),
        ),
        migrations.AlterField(
            model_name='pizza_ing',
            name='fk_ingrediente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Ingrediente', verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='pizza_ing',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Pedido', verbose_name='Pedidos'),
        ),
        migrations.AlterField(
            model_name='pizza_ing',
            name='fk_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzeria.Pizza', verbose_name='Pizzas'),
        ),
    ]
