# Generated by Django 3.0.8 on 2020-08-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0007_auto_20200801_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
